env:
  database: "off"

ingressController:
  enabled: false

dblessConfig:
  config: |
    _format_version: "1.1"
    services:
      - name: companyservice
        url: http://companybackend.default.svc.cluster.local:8030
        routes:
          - name: companyroute
            paths:
            - "/companyapi"
      - name: listingservice
        url: http://listingbackend.default.svc.cluster.local:8020
        routes:
          - name: listingroute
            paths:
            - "/listingapi"

certificates:
  admin:
    enabled: true
    # Set `issuer` or `clusterIssuer` to name of alternate cert-manager clusterIssuer to override default
    # self-signed issuer.
    issuer: ""
    clusterIssuer: ""
    # Use commonName and dnsNames to set the common name and dns alt names which this
    # certificate is valid for. Wildcard records are supported by the included self-signed issuer.
    commonName: "kong.example"
    # Remove the "[]" and uncomment/change the examples to add SANs
    dnsNames: []